### ISSUE TITLE
program hangs and runs within while loop

### ISSUE THREAD

**Issue by vtronicsautomation** [KalleHallden/WeatherPredictor#1]
`Warning (from warnings module):
  File "C:\Python\lib\site-packages\sklearn\externals\joblib\__init__.py", line 15
    warnings.warn(msg, category=DeprecationWarning)
DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
************************************************
---------- What would you like to do? ----------

1. Look up the weather on a specific day
2. Predict the weather on a specific day

Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
Enter option: 3
`

**Comment by vtronicsautomation** [comment]
solved issues by upgrading all the libraries again

**Comment by anant0418** [comment]
I am running on Anaconda and program doesn't move out of while loop. Plz how to solve it?
